name: Build and Publish Docker

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: yt-bot
            ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Lowercase the repo owner
              run: |
                  echo ::set-env name=IMAGE::${GITHUB_REPOSITORY_OWNER,,}/${IMAGE_NAME,,}
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  platforms: linux/amd64,linux/arm64
                  context: .
                  push: true
                  tags: |
                      ghcr.io/${{ env.IMAGE }}:latest
                      ghcr.io/${{ env.IMAGE }}:${{ github.sha }}
